# Generated by Django 2.2.23 on 2021-05-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurencyFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10)),
                ('currency_symbol', models.CharField(max_length=30)),
                ('currency_code', models.CharField(max_length=30)),
                ('currency_nomenclature', models.CharField(max_length=30)),
                ('currency_symbol_pos', models.CharField(max_length=30)),
                ('cents_enabled', models.BooleanField(default=False)),
                ('display_format', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('country', 'currency_code')},
            },
        ),
    ]
